/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BankDetails {
  'ifscCode' : string,
  'bankName' : string,
  'cancelledCheque' : [] | [ExternalBlob],
  'upiId' : [] | [string],
  'accountNumber' : string,
  'accountHolder' : string,
}
export interface Declaration { 'date' : string, 'signatureDataUrl' : string }
export interface Education {
  'cert10' : [] | [ExternalBlob],
  'cert12' : [] | [ExternalBlob],
  'bachelor' : [] | [ExternalBlob],
  'master' : [] | [ExternalBlob],
  'qualification' : string,
  'diploma' : [] | [ExternalBlob],
}
export type EmployeeStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'inactive' : null };
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface InductionForm {
  'kyc' : KYC,
  'status' : EmployeeStatus,
  'bankDetails' : BankDetails,
  'education' : Education,
  'submittedAt' : bigint,
  'declaration' : Declaration,
  'employeeId' : [] | [string],
  'personalInfo' : PersonalInfo,
  'workProfile' : WorkProfile,
}
export interface InductionFormInput {
  'kyc' : KYC,
  'bankDetails' : BankDetails,
  'education' : Education,
  'declaration' : Declaration,
  'personalInfo' : PersonalInfo,
  'workProfile' : WorkProfile,
}
export interface KYC {
  'passportPhoto' : [] | [ExternalBlob],
  'panCard' : [] | [ExternalBlob],
  'panNumber' : string,
  'aadhaarCard' : [] | [ExternalBlob],
  'aadhaarNumber' : string,
}
export interface PersonalInfo {
  'dob' : string,
  'alternatePhone' : string,
  'fullName' : string,
  'email' : string,
  'address' : string,
  'gender' : Gender,
  'phone' : string,
}
export interface TotalStats {
  'total' : bigint,
  'active' : bigint,
  'pending' : bigint,
  'inactive' : bigint,
}
export interface WorkProfile {
  'experienceDetails' : string,
  'typesOfCalling' : Array<string>,
  'salarySlip1' : [] | [ExternalBlob],
  'salarySlip2' : [] | [ExternalBlob],
  'salarySlip3' : [] | [ExternalBlob],
  'experienceCertificate' : [] | [ExternalBlob],
  'hasExperience' : boolean,
  'relievingLetter' : [] | [ExternalBlob],
  'postsApplying' : Array<string>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'adminLogin' : ActorMethod<[string, string], string>,
  'assignEmployeeId' : ActorMethod<[string, string, string], undefined>,
  'changePassword' : ActorMethod<[string, string], undefined>,
  'deleteSubmission' : ActorMethod<[string, string], undefined>,
  'getAllSubmissions' : ActorMethod<[string], Array<InductionForm>>,
  'getSubmission' : ActorMethod<[string, string], InductionForm>,
  'getTotalStats' : ActorMethod<[], TotalStats>,
  'submitInductionForm' : ActorMethod<[InductionFormInput], string>,
  'updateStatus' : ActorMethod<[string, string, EmployeeStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];