/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const KYC = IDL.Record({
  'passportPhoto' : IDL.Opt(ExternalBlob),
  'panCard' : IDL.Opt(ExternalBlob),
  'panNumber' : IDL.Text,
  'aadhaarCard' : IDL.Opt(ExternalBlob),
  'aadhaarNumber' : IDL.Text,
});
export const EmployeeStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'inactive' : IDL.Null,
});
export const BankDetails = IDL.Record({
  'ifscCode' : IDL.Text,
  'bankName' : IDL.Text,
  'cancelledCheque' : IDL.Opt(ExternalBlob),
  'upiId' : IDL.Opt(IDL.Text),
  'accountNumber' : IDL.Text,
  'accountHolder' : IDL.Text,
});
export const Education = IDL.Record({
  'cert10' : IDL.Opt(ExternalBlob),
  'cert12' : IDL.Opt(ExternalBlob),
  'bachelor' : IDL.Opt(ExternalBlob),
  'master' : IDL.Opt(ExternalBlob),
  'qualification' : IDL.Text,
  'diploma' : IDL.Opt(ExternalBlob),
});
export const Declaration = IDL.Record({
  'date' : IDL.Text,
  'signatureDataUrl' : IDL.Text,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const PersonalInfo = IDL.Record({
  'dob' : IDL.Text,
  'alternatePhone' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'gender' : Gender,
  'phone' : IDL.Text,
});
export const WorkProfile = IDL.Record({
  'experienceDetails' : IDL.Text,
  'typesOfCalling' : IDL.Vec(IDL.Text),
  'salarySlip1' : IDL.Opt(ExternalBlob),
  'salarySlip2' : IDL.Opt(ExternalBlob),
  'salarySlip3' : IDL.Opt(ExternalBlob),
  'experienceCertificate' : IDL.Opt(ExternalBlob),
  'hasExperience' : IDL.Bool,
  'relievingLetter' : IDL.Opt(ExternalBlob),
  'postsApplying' : IDL.Vec(IDL.Text),
});
export const InductionForm = IDL.Record({
  'kyc' : KYC,
  'status' : EmployeeStatus,
  'bankDetails' : BankDetails,
  'education' : Education,
  'submittedAt' : IDL.Int,
  'declaration' : Declaration,
  'employeeId' : IDL.Opt(IDL.Text),
  'personalInfo' : PersonalInfo,
  'workProfile' : WorkProfile,
});
export const TotalStats = IDL.Record({
  'total' : IDL.Nat,
  'active' : IDL.Nat,
  'pending' : IDL.Nat,
  'inactive' : IDL.Nat,
});
export const InductionFormInput = IDL.Record({
  'kyc' : KYC,
  'bankDetails' : BankDetails,
  'education' : Education,
  'declaration' : Declaration,
  'personalInfo' : PersonalInfo,
  'workProfile' : WorkProfile,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'assignEmployeeId' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteSubmission' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllSubmissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(InductionForm)],
      ['query'],
    ),
  'getSubmission' : IDL.Func([IDL.Text, IDL.Text], [InductionForm], ['query']),
  'getTotalStats' : IDL.Func([], [TotalStats], ['query']),
  'submitInductionForm' : IDL.Func([InductionFormInput], [IDL.Text], []),
  'updateStatus' : IDL.Func([IDL.Text, IDL.Text, EmployeeStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const KYC = IDL.Record({
    'passportPhoto' : IDL.Opt(ExternalBlob),
    'panCard' : IDL.Opt(ExternalBlob),
    'panNumber' : IDL.Text,
    'aadhaarCard' : IDL.Opt(ExternalBlob),
    'aadhaarNumber' : IDL.Text,
  });
  const EmployeeStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const BankDetails = IDL.Record({
    'ifscCode' : IDL.Text,
    'bankName' : IDL.Text,
    'cancelledCheque' : IDL.Opt(ExternalBlob),
    'upiId' : IDL.Opt(IDL.Text),
    'accountNumber' : IDL.Text,
    'accountHolder' : IDL.Text,
  });
  const Education = IDL.Record({
    'cert10' : IDL.Opt(ExternalBlob),
    'cert12' : IDL.Opt(ExternalBlob),
    'bachelor' : IDL.Opt(ExternalBlob),
    'master' : IDL.Opt(ExternalBlob),
    'qualification' : IDL.Text,
    'diploma' : IDL.Opt(ExternalBlob),
  });
  const Declaration = IDL.Record({
    'date' : IDL.Text,
    'signatureDataUrl' : IDL.Text,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const PersonalInfo = IDL.Record({
    'dob' : IDL.Text,
    'alternatePhone' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'gender' : Gender,
    'phone' : IDL.Text,
  });
  const WorkProfile = IDL.Record({
    'experienceDetails' : IDL.Text,
    'typesOfCalling' : IDL.Vec(IDL.Text),
    'salarySlip1' : IDL.Opt(ExternalBlob),
    'salarySlip2' : IDL.Opt(ExternalBlob),
    'salarySlip3' : IDL.Opt(ExternalBlob),
    'experienceCertificate' : IDL.Opt(ExternalBlob),
    'hasExperience' : IDL.Bool,
    'relievingLetter' : IDL.Opt(ExternalBlob),
    'postsApplying' : IDL.Vec(IDL.Text),
  });
  const InductionForm = IDL.Record({
    'kyc' : KYC,
    'status' : EmployeeStatus,
    'bankDetails' : BankDetails,
    'education' : Education,
    'submittedAt' : IDL.Int,
    'declaration' : Declaration,
    'employeeId' : IDL.Opt(IDL.Text),
    'personalInfo' : PersonalInfo,
    'workProfile' : WorkProfile,
  });
  const TotalStats = IDL.Record({
    'total' : IDL.Nat,
    'active' : IDL.Nat,
    'pending' : IDL.Nat,
    'inactive' : IDL.Nat,
  });
  const InductionFormInput = IDL.Record({
    'kyc' : KYC,
    'bankDetails' : BankDetails,
    'education' : Education,
    'declaration' : Declaration,
    'personalInfo' : PersonalInfo,
    'workProfile' : WorkProfile,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'assignEmployeeId' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteSubmission' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InductionForm)],
        ['query'],
      ),
    'getSubmission' : IDL.Func(
        [IDL.Text, IDL.Text],
        [InductionForm],
        ['query'],
      ),
    'getTotalStats' : IDL.Func([], [TotalStats], ['query']),
    'submitInductionForm' : IDL.Func([InductionFormInput], [IDL.Text], []),
    'updateStatus' : IDL.Func([IDL.Text, IDL.Text, EmployeeStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };