/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Declaration {
    date: string;
    signatureDataUrl: string;
}
export interface InductionFormInput {
    kyc: KYC;
    bankDetails: BankDetails;
    education: Education;
    declaration: Declaration;
    personalInfo: PersonalInfo;
    workProfile: WorkProfile;
}
export interface Education {
    cert10?: ExternalBlob;
    cert12?: ExternalBlob;
    bachelor?: ExternalBlob;
    master?: ExternalBlob;
    qualification: string;
    diploma?: ExternalBlob;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface InductionForm {
    kyc: KYC;
    status: EmployeeStatus;
    bankDetails: BankDetails;
    education: Education;
    submittedAt: bigint;
    declaration: Declaration;
    employeeId?: string;
    personalInfo: PersonalInfo;
    workProfile: WorkProfile;
}
export interface PersonalInfo {
    dob: string;
    alternatePhone: string;
    fullName: string;
    email: string;
    address: string;
    gender: Gender;
    phone: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface WorkProfile {
    experienceDetails: string;
    typesOfCalling: Array<string>;
    salarySlip1?: ExternalBlob;
    salarySlip2?: ExternalBlob;
    salarySlip3?: ExternalBlob;
    experienceCertificate?: ExternalBlob;
    hasExperience: boolean;
    relievingLetter?: ExternalBlob;
    postsApplying: Array<string>;
}
export interface BankDetails {
    ifscCode: string;
    bankName: string;
    cancelledCheque?: ExternalBlob;
    upiId?: string;
    accountNumber: string;
    accountHolder: string;
}
export interface KYC {
    passportPhoto?: ExternalBlob;
    panCard?: ExternalBlob;
    panNumber: string;
    aadhaarCard?: ExternalBlob;
    aadhaarNumber: string;
}
export interface TotalStats {
    total: bigint;
    active: bigint;
    pending: bigint;
    inactive: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum EmployeeStatus {
    active = "active",
    pending = "pending",
    inactive = "inactive"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    adminLogin(username: string, password: string): Promise<string>;
    assignEmployeeId(token: string, id: string, employeeId: string): Promise<void>;
    changePassword(token: string, newPassword: string): Promise<void>;
    deleteSubmission(token: string, id: string): Promise<void>;
    getAllSubmissions(token: string): Promise<Array<InductionForm>>;
    getSubmission(token: string, id: string): Promise<InductionForm>;
    getTotalStats(): Promise<TotalStats>;
    submitInductionForm(form: InductionFormInput): Promise<string>;
    updateStatus(token: string, id: string, status: EmployeeStatus): Promise<void>;
}
import type { BankDetails as _BankDetails, Declaration as _Declaration, Education as _Education, EmployeeStatus as _EmployeeStatus, ExternalBlob as _ExternalBlob, Gender as _Gender, InductionForm as _InductionForm, InductionFormInput as _InductionFormInput, KYC as _KYC, PersonalInfo as _PersonalInfo, WorkProfile as _WorkProfile, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async assignEmployeeId(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignEmployeeId(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignEmployeeId(arg0, arg1, arg2);
            return result;
        }
    }
    async changePassword(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changePassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePassword(arg0, arg1);
            return result;
        }
    }
    async deleteSubmission(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubmission(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubmission(arg0, arg1);
            return result;
        }
    }
    async getAllSubmissions(arg0: string): Promise<Array<InductionForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmission(arg0: string, arg1: string): Promise<InductionForm> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmission(arg0, arg1);
                return from_candid_InductionForm_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmission(arg0, arg1);
            return from_candid_InductionForm_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalStats(): Promise<TotalStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalStats();
            return result;
        }
    }
    async submitInductionForm(arg0: InductionFormInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInductionForm(await to_candid_InductionFormInput_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInductionForm(await to_candid_InductionFormInput_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateStatus(arg0: string, arg1: string, arg2: EmployeeStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStatus(arg0, arg1, to_candid_EmployeeStatus_n43(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStatus(arg0, arg1, to_candid_EmployeeStatus_n43(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
async function from_candid_BankDetails_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankDetails): Promise<BankDetails> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_Education_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Education): Promise<Education> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_EmployeeStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeStatus): EmployeeStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Gender_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_InductionForm_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InductionForm): Promise<InductionForm> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_KYC_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KYC): Promise<KYC> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PersonalInfo_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonalInfo): PersonalInfo {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_WorkProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkProfile): Promise<WorkProfile> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kyc: _KYC;
    status: _EmployeeStatus;
    bankDetails: _BankDetails;
    education: _Education;
    submittedAt: bigint;
    declaration: _Declaration;
    employeeId: [] | [string];
    personalInfo: _PersonalInfo;
    workProfile: _WorkProfile;
}): Promise<{
    kyc: KYC;
    status: EmployeeStatus;
    bankDetails: BankDetails;
    education: Education;
    submittedAt: bigint;
    declaration: Declaration;
    employeeId?: string;
    personalInfo: PersonalInfo;
    workProfile: WorkProfile;
}> {
    return {
        kyc: await from_candid_KYC_n11(_uploadFile, _downloadFile, value.kyc),
        status: from_candid_EmployeeStatus_n15(_uploadFile, _downloadFile, value.status),
        bankDetails: await from_candid_BankDetails_n17(_uploadFile, _downloadFile, value.bankDetails),
        education: await from_candid_Education_n20(_uploadFile, _downloadFile, value.education),
        submittedAt: value.submittedAt,
        declaration: value.declaration,
        employeeId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.employeeId)),
        personalInfo: from_candid_PersonalInfo_n22(_uploadFile, _downloadFile, value.personalInfo),
        workProfile: await from_candid_WorkProfile_n26(_uploadFile, _downloadFile, value.workProfile)
    };
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    passportPhoto: [] | [_ExternalBlob];
    panCard: [] | [_ExternalBlob];
    panNumber: string;
    aadhaarCard: [] | [_ExternalBlob];
    aadhaarNumber: string;
}): Promise<{
    passportPhoto?: ExternalBlob;
    panCard?: ExternalBlob;
    panNumber: string;
    aadhaarCard?: ExternalBlob;
    aadhaarNumber: string;
}> {
    return {
        passportPhoto: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.passportPhoto)),
        panCard: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.panCard)),
        panNumber: value.panNumber,
        aadhaarCard: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.aadhaarCard)),
        aadhaarNumber: value.aadhaarNumber
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ifscCode: string;
    bankName: string;
    cancelledCheque: [] | [_ExternalBlob];
    upiId: [] | [string];
    accountNumber: string;
    accountHolder: string;
}): Promise<{
    ifscCode: string;
    bankName: string;
    cancelledCheque?: ExternalBlob;
    upiId?: string;
    accountNumber: string;
    accountHolder: string;
}> {
    return {
        ifscCode: value.ifscCode,
        bankName: value.bankName,
        cancelledCheque: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.cancelledCheque)),
        upiId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.upiId)),
        accountNumber: value.accountNumber,
        accountHolder: value.accountHolder
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cert10: [] | [_ExternalBlob];
    cert12: [] | [_ExternalBlob];
    bachelor: [] | [_ExternalBlob];
    master: [] | [_ExternalBlob];
    qualification: string;
    diploma: [] | [_ExternalBlob];
}): Promise<{
    cert10?: ExternalBlob;
    cert12?: ExternalBlob;
    bachelor?: ExternalBlob;
    master?: ExternalBlob;
    qualification: string;
    diploma?: ExternalBlob;
}> {
    return {
        cert10: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.cert10)),
        cert12: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.cert12)),
        bachelor: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.bachelor)),
        master: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.master)),
        qualification: value.qualification,
        diploma: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.diploma))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dob: string;
    alternatePhone: string;
    fullName: string;
    email: string;
    address: string;
    gender: _Gender;
    phone: string;
}): {
    dob: string;
    alternatePhone: string;
    fullName: string;
    email: string;
    address: string;
    gender: Gender;
    phone: string;
} {
    return {
        dob: value.dob,
        alternatePhone: value.alternatePhone,
        fullName: value.fullName,
        email: value.email,
        address: value.address,
        gender: from_candid_Gender_n24(_uploadFile, _downloadFile, value.gender),
        phone: value.phone
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceDetails: string;
    typesOfCalling: Array<string>;
    salarySlip1: [] | [_ExternalBlob];
    salarySlip2: [] | [_ExternalBlob];
    salarySlip3: [] | [_ExternalBlob];
    experienceCertificate: [] | [_ExternalBlob];
    hasExperience: boolean;
    relievingLetter: [] | [_ExternalBlob];
    postsApplying: Array<string>;
}): Promise<{
    experienceDetails: string;
    typesOfCalling: Array<string>;
    salarySlip1?: ExternalBlob;
    salarySlip2?: ExternalBlob;
    salarySlip3?: ExternalBlob;
    experienceCertificate?: ExternalBlob;
    hasExperience: boolean;
    relievingLetter?: ExternalBlob;
    postsApplying: Array<string>;
}> {
    return {
        experienceDetails: value.experienceDetails,
        typesOfCalling: value.typesOfCalling,
        salarySlip1: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.salarySlip1)),
        salarySlip2: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.salarySlip2)),
        salarySlip3: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.salarySlip3)),
        experienceCertificate: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.experienceCertificate)),
        hasExperience: value.hasExperience,
        relievingLetter: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.relievingLetter)),
        postsApplying: value.postsApplying
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    inactive: null;
}): EmployeeStatus {
    return "active" in value ? EmployeeStatus.active : "pending" in value ? EmployeeStatus.pending : "inactive" in value ? EmployeeStatus.inactive : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
async function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InductionForm>): Promise<Array<InductionForm>> {
    return await Promise.all(value.map(async (x)=>await from_candid_InductionForm_n9(_uploadFile, _downloadFile, x)));
}
async function to_candid_BankDetails_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BankDetails): Promise<_BankDetails> {
    return await to_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_Education_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Education): Promise<_Education> {
    return await to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeStatus): _EmployeeStatus {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Gender_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
async function to_candid_InductionFormInput_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InductionFormInput): Promise<_InductionFormInput> {
    return await to_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function to_candid_KYC_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KYC): Promise<_KYC> {
    return await to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_PersonalInfo_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonalInfo): _PersonalInfo {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function to_candid_WorkProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkProfile): Promise<_WorkProfile> {
    return await to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kyc: KYC;
    bankDetails: BankDetails;
    education: Education;
    declaration: Declaration;
    personalInfo: PersonalInfo;
    workProfile: WorkProfile;
}): Promise<{
    kyc: _KYC;
    bankDetails: _BankDetails;
    education: _Education;
    declaration: _Declaration;
    personalInfo: _PersonalInfo;
    workProfile: _WorkProfile;
}> {
    return {
        kyc: await to_candid_KYC_n30(_uploadFile, _downloadFile, value.kyc),
        bankDetails: await to_candid_BankDetails_n33(_uploadFile, _downloadFile, value.bankDetails),
        education: await to_candid_Education_n35(_uploadFile, _downloadFile, value.education),
        declaration: value.declaration,
        personalInfo: to_candid_PersonalInfo_n37(_uploadFile, _downloadFile, value.personalInfo),
        workProfile: await to_candid_WorkProfile_n41(_uploadFile, _downloadFile, value.workProfile)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    passportPhoto?: ExternalBlob;
    panCard?: ExternalBlob;
    panNumber: string;
    aadhaarCard?: ExternalBlob;
    aadhaarNumber: string;
}): Promise<{
    passportPhoto: [] | [_ExternalBlob];
    panCard: [] | [_ExternalBlob];
    panNumber: string;
    aadhaarCard: [] | [_ExternalBlob];
    aadhaarNumber: string;
}> {
    return {
        passportPhoto: value.passportPhoto ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.passportPhoto)) : candid_none(),
        panCard: value.panCard ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.panCard)) : candid_none(),
        panNumber: value.panNumber,
        aadhaarCard: value.aadhaarCard ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.aadhaarCard)) : candid_none(),
        aadhaarNumber: value.aadhaarNumber
    };
}
async function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ifscCode: string;
    bankName: string;
    cancelledCheque?: ExternalBlob;
    upiId?: string;
    accountNumber: string;
    accountHolder: string;
}): Promise<{
    ifscCode: string;
    bankName: string;
    cancelledCheque: [] | [_ExternalBlob];
    upiId: [] | [string];
    accountNumber: string;
    accountHolder: string;
}> {
    return {
        ifscCode: value.ifscCode,
        bankName: value.bankName,
        cancelledCheque: value.cancelledCheque ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.cancelledCheque)) : candid_none(),
        upiId: value.upiId ? candid_some(value.upiId) : candid_none(),
        accountNumber: value.accountNumber,
        accountHolder: value.accountHolder
    };
}
async function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cert10?: ExternalBlob;
    cert12?: ExternalBlob;
    bachelor?: ExternalBlob;
    master?: ExternalBlob;
    qualification: string;
    diploma?: ExternalBlob;
}): Promise<{
    cert10: [] | [_ExternalBlob];
    cert12: [] | [_ExternalBlob];
    bachelor: [] | [_ExternalBlob];
    master: [] | [_ExternalBlob];
    qualification: string;
    diploma: [] | [_ExternalBlob];
}> {
    return {
        cert10: value.cert10 ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.cert10)) : candid_none(),
        cert12: value.cert12 ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.cert12)) : candid_none(),
        bachelor: value.bachelor ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.bachelor)) : candid_none(),
        master: value.master ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.master)) : candid_none(),
        qualification: value.qualification,
        diploma: value.diploma ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.diploma)) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dob: string;
    alternatePhone: string;
    fullName: string;
    email: string;
    address: string;
    gender: Gender;
    phone: string;
}): {
    dob: string;
    alternatePhone: string;
    fullName: string;
    email: string;
    address: string;
    gender: _Gender;
    phone: string;
} {
    return {
        dob: value.dob,
        alternatePhone: value.alternatePhone,
        fullName: value.fullName,
        email: value.email,
        address: value.address,
        gender: to_candid_Gender_n39(_uploadFile, _downloadFile, value.gender),
        phone: value.phone
    };
}
async function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceDetails: string;
    typesOfCalling: Array<string>;
    salarySlip1?: ExternalBlob;
    salarySlip2?: ExternalBlob;
    salarySlip3?: ExternalBlob;
    experienceCertificate?: ExternalBlob;
    hasExperience: boolean;
    relievingLetter?: ExternalBlob;
    postsApplying: Array<string>;
}): Promise<{
    experienceDetails: string;
    typesOfCalling: Array<string>;
    salarySlip1: [] | [_ExternalBlob];
    salarySlip2: [] | [_ExternalBlob];
    salarySlip3: [] | [_ExternalBlob];
    experienceCertificate: [] | [_ExternalBlob];
    hasExperience: boolean;
    relievingLetter: [] | [_ExternalBlob];
    postsApplying: Array<string>;
}> {
    return {
        experienceDetails: value.experienceDetails,
        typesOfCalling: value.typesOfCalling,
        salarySlip1: value.salarySlip1 ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.salarySlip1)) : candid_none(),
        salarySlip2: value.salarySlip2 ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.salarySlip2)) : candid_none(),
        salarySlip3: value.salarySlip3 ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.salarySlip3)) : candid_none(),
        experienceCertificate: value.experienceCertificate ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.experienceCertificate)) : candid_none(),
        hasExperience: value.hasExperience,
        relievingLetter: value.relievingLetter ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.relievingLetter)) : candid_none(),
        postsApplying: value.postsApplying
    };
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeStatus): {
    active: null;
} | {
    pending: null;
} | {
    inactive: null;
} {
    return value == EmployeeStatus.active ? {
        active: null
    } : value == EmployeeStatus.pending ? {
        pending: null
    } : value == EmployeeStatus.inactive ? {
        inactive: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
